### PR TITLE
Only yield output neighbours in petgraph's IntoNeighbors trait

### PR DESCRIPTION
**Pull request by aborgna-q**

### CODE REVIEW

**Review by acl-cqc — APPROVED** [review]
Yes, but it would be nice to trial this with Hugr first and see that it behaves as I expect; can you run me through how to do that?

**Comment by aborgna-q** [comment]
I checked it on `hugr/main`.

If you have a local clone, you can add a `path = "../portgraph"` attribute to the dependency in `Cargo.toml`.
Alternatively, you can get it from github
```
git="https://github.com/CQCL/hugr", branch="fix/petgraph-neighbours"
```

**Comment by acl-cqc** [comment]
Hmmmm, I put a panic in here and yet the Hugr code using petgraph DfsPostOrder doesn't panic. Maybe there's another place?

**Comment by acl-cqc** [comment]
Ok, so turns out this isn't the code we are using in Hugr, so we are at the level of "it looks wrong", but I'll stand by that it does look wrong and this PR looks like a fix and I have approved it :)

**Comment by aborgna-q** [comment]
It's part of the `IntoNeighbors` [definition](https://docs.rs/petgraph/latest/petgraph/visit/trait.IntoNeighbors.html):

>The neighbors are, depending on the graph’s edge type:
>
> - Directed: All targets of edges from a.

**Pull request merged**
