### PR TITLE
Generalise toposort to LinkView

### PR DESCRIPTION
**Pull request by lmondada**

### CODE REVIEW

**Comment by lmondada** [comment]
Sorry, messed up my git manip, will be ready soon!

**Comment by lmondada** [comment]
It's ready now!

**Comment by lmondada** [comment]
Side note: this could also be implemented on any `petgraph`, but thought that it would be odd to have a `petgraph`-only algo in `portgraph`, so I prefered the `LinkView`-implementation.

**Review by aborgna-q — APPROVED** [review]
Nice!

Petgraph already has a toposort algo. There's a benchmark here that compares both implementations (and petgraph's was faster last time I checked!)
image

That implementation allocates a vector with the result instead of returning the iterator. We currently use petgraph's in Hugr, but imho both are useful.

**Pull request merged**
