### PR TITLE
Add trait impls for refs

### LINKED ISSUE #93: Implement more `petgraph` traits
I noticed that `portgraph`'s traits (`PortView`, `LinkView`) are implemented for graph objects themselves, whereas most `petgraph` traits (at least the ones I am using) are implemented for graph references.

Is there anything that prevents us from defining
```rust
impl<'a, G: PortView> PortView for &'a G { ... }
```
within `portgraph`?

Whilst we are at it, are the following impls (among other) also possible?
```rust
impl<G: PortView> GraphBase for G { 
    type NodeId = NodeIndex;
    ...
}
impl<'a, G: PortView> IntoNodeIndices for &'a G { ... } 
...
```

Such `impl`s would greatly simplify my generics and bounds.

I might not too confident yet about which trait impls are exactly allowed in Rust, so it might be that some of those are invalid.

EDIT: it might be slightly weird if e.g. `IntoNodeIndices` is defined both for graphs themselves and their references, as calling `g.node_identifiers()` would consume `g` in the absence of explicit casting... I changed the second code block to only implement `IntoNodeIndices` for refs.

### PR DESCRIPTION
**Pull request by lmondada**
Closes #93

### CODE REVIEW

**Comment by lmondada** [comment]
Closes #94

**Comment by lmondada** [comment]
@aborgna-q What do you think of this solution? Do you see a less verbose way? We'd have to do the same for `&mut` for both mutable and immutable types...

The better solution would probably to fix `auto_impl` to support GATs (if that is really the problem), but I don't have time to do that now.

**Comment by aborgna-q** [comment]
- I'm ok with adding this, but what's your usecase?
- You could use `delegate!` to reduce the boilerplate:

```rust

    delegate! {
        to (*self) {
            fn port_direction(&self, port: impl Into<PortIndex>) -> Option<Direction>;
            fn port_node(&self, port: impl Into<PortIndex>) -> Option<NodeIndex>;
            ...
        }
    }
```
(see `filter.rs`)

**Comment by lmondada** [comment]
I have a matcher trait with the following method

```rust
trait Matcher<G: GraphBase> {
    fn find_rooted_matches(&self, G, root: <G as GraphBase>::NodeId);

    fn find_matches(&self, G) where G: petgraph::visit::IntoNodeIndices {
        // some code that requires petgraph::visit::IntoNodeIndices
    }
}
```

For the implemenation, it's nicer to write
```rust
impl<G> Matcher<G> for SinglePatternMatcher<U, (), UnweightedEdge>
where
    G: LinkView + GraphBase<NodeId = NodeIndex>
{ ... }
```

rather than

```rust
impl<'g, G> Matcher<&'g G> for SinglePatternMatcher<U, (), UnweightedEdge>
where
    G: LinkView
    &G: GraphBase<NodeId = NodeIndex> + IntoNodeIndices
{ ... }
```
(if that syntax is even valid?)

Does that make sense?

**Comment by aborgna-q** [comment]
_s/IntoNodeIndices/IntoNodeIdentifiers/_.

It may be annoying to write if you ever have a generic `Matcher`, but I think that'll work.

**Review by aborgna-q — APPROVED** [review]
LGTM

**Pull request merged**
